import { AuditIssue, KnowledgeDoc } from '../../../types';

/**
 * 经验层 —— 把「这次踩的坑」变成下次能被检索到的一句话。
 *
 * ══════════════════════════════════════════════════════════════
 * 三层知识里，这一层最值钱也最难攒
 * ══════════════════════════════════════════════════════════════
 *
 *   ① 事实层  标准原文、官方文件         —— 网上就有，谁都能查
 *   ② 经验层  我们自己踩出来的           —— **只有我们有**
 *   ③ 检索层  问一句话能把前两层捞出来   —— 见 retrieval.ts
 *
 * 第二层是信义真正的护城河：ISO 9001 的条文全世界一样，
 * 但「温州塑编厂做 SC 认证，车间隔离最容易被外审挑」这种话，
 * 只有做过的人知道。
 *
 * 而它最难攒的原因是：**经验产生的那一刻，人正忙着别的事。**
 * 不符合项关闭的时候，顾问脑子里想的是「终于闭环了」，
 * 不是「我该记点什么下来」。等他闲下来，细节已经忘了。
 *
 * ── 所以在关闭的那一刻问一句 ──────────────────────────────────
 *
 * 就一个输入框：「这次的教训，下次怎么避免？」
 * 不填也能关 —— 强制填只会得到「无」和「已整改」这种废话，
 * 而废话进了知识库比没有更糟：它会挤占检索位置。
 *
 * ── 为什么不让 AI 自动提炼 ────────────────────────────────────
 *
 * 试过这个念头，放弃了。AI 能从「findings + rectificationPlan」
 * 生成一段通顺的总结，但那段总结**只是把已有文字换个说法**，
 * 没有新增任何信息 —— 而它看起来很权威，会被当成经验引用。
 *
 * 真正有价值的那一句（「这家的问题其实出在采购没留验收记录，
 * 车间只是表象」）只在人脑子里，AI 从工单文本里推不出来。
 *
 * **人写那一句，机器补齐所有能自动带上的上下文。** 分工就该这样。
 */

/** 一条经验值不值得存 */
export const isLessonWorthKeeping = (text: string): { ok: boolean; reason?: string } => {
  const t = String(text || '').trim();
  if (!t) return { ok: false, reason: '没填' };
  if (t.length < 8) return { ok: false, reason: '太短了，看不出下次该怎么做' };
  /*
    挡掉「无 / 没有 / 已整改 / 已闭环」这类。
    它们进了知识库不是"多一条"，是**挤掉真正有用的那条** ——
    检索按相关度取前几篇，废话也占位置。
  */
  if (/^(无|没有|不适用|N\/?A|已整改|已完成|已闭环|正常|OK)$/i.test(t)) {
    return { ok: false, reason: '这句话下次帮不上忙，不如不存' };
  }
  return { ok: true };
};

/**
 * 把一条关闭的不符合项 + 人写的那句教训，做成一份知识条目。
 *
 * 上下文（行业、标准、严重程度、客户）全部自动带上 ——
 * 人只需要写他脑子里那一句。**每多要求填一个字段，
 * 就多一个人跳过这一步的理由。**
 */
export const buildLessonDoc = (params: {
  issue: AuditIssue;
  lesson: string;
  author: string;
  /** 客户所属行业，从客户档案带过来 */
  industry?: string;
  /** 涉及的标准，如 ['ISO 9001'] */
  standards?: string[];
}): Omit<KnowledgeDoc, 'id'> => {
  const { issue, lesson, author, industry, standards } = params;
  const today = new Date();
  const p2 = (n: number) => String(n).padStart(2, '0');
  const dateStr = `${today.getFullYear()}-${p2(today.getMonth() + 1)}-${p2(today.getDate())}`;

  const severityLabel = issue.severity === 'Major' ? '严重不符合'
    : issue.severity === 'Minor' ? '一般不符合' : '观察项';

  /*
    标题要能在检索结果里一眼认出来：行业 + 标准 + 问题。
    「经验｜塑编 SC｜车间隔离不到位」比「关于XX公司的整改总结」有用得多 ——
    后者只有点开才知道讲什么。
  */
  const titleBits = [industry, (standards || [])[0]].filter(Boolean).join(' ');
  const title = `经验｜${titleBits || '通用'}｜${issue.findings.slice(0, 20)}`;

  const content = [
    `## 下次怎么避免`,
    lesson.trim(),
    ``,
    `## 这次发生了什么`,
    `- 客户：${issue.customerName}`,
    `- 严重程度：${severityLabel}`,
    `- 发现的问题：${issue.findings}`,
    issue.rectificationPlan ? `- 整改措施：${issue.rectificationPlan}` : '',
    issue.auditType ? `- 审核类型：${issue.auditType}` : '',
    ``,
    `> 由「不符合项 ${issue.id}」关闭时记录，记录人 ${author}，${dateStr}。`,
  ].filter(Boolean).join('\n');

  return {
    title,
    category: '经验沉淀',
    format: 'md',
    size: `${Math.ceil(content.length / 1024)}KB`,
    updatedAt: dateStr,
    content,
    summary: lesson.trim().slice(0, 120),
    /*
      默认进 AI 语料 —— 这一层就是为了喂 AI 而存在的。
      和上传文件不同：文件可能含客户经营数据要挡（见 intake.ts），
      而这里的内容是**我们自己写的一句方法论**，没有那个风险。
    */
    aiVisible: true,
    linkType: 'audit',
    linkId: issue.id,
    linkTitle: `${issue.customerName} · ${severityLabel}`,
    source: 'system',
    autoGenerated: false,
    /*
      **必须标成 ourExperience，不能是 official。**
      AI 引用时要说「据我们以往经验」，而不是当成标准规定 ——
      经验说错了是判断失误，标准说错了是专业事故。
    */
    trustLevel: 'ourExperience',
    industry,
    standards,
    tags: ['经验', '不符合项', severityLabel, industry, ...(standards || [])].filter(Boolean) as string[],
    reviewedAt: dateStr,
    reviewedBy: author,
  };
};
