// 知识库 repo —— 批次2。注意 updatedAt 是业务字段，映射到 doc_updated_at。
const { query } = require('../db/pool');
const { buildMapper, makeId } = require('./_mapper');

const SPEC = [
  { api: 'id', col: 'id', kind: 'text' },
  { api: 'title', col: 'title', kind: 'text' },
  { api: 'category', col: 'category', kind: 'text' },
  { api: 'format', col: 'format', kind: 'text' },
  { api: 'size', col: 'size', kind: 'text' },
  { api: 'updatedAt', col: 'doc_updated_at', kind: 'text' },
  { api: 'content', col: 'content', kind: 'text' },
  { api: 'summary', col: 'summary', kind: 'text' },
  { api: 'aiVisible', col: 'ai_visible', kind: 'bool' },
  { api: 'sourceUrl', col: 'source_url', kind: 'text' },
  { api: 'linkType', col: 'link_type', kind: 'text' },
  { api: 'linkId', col: 'link_id', kind: 'text' },
  { api: 'linkTitle', col: 'link_title', kind: 'text' },
  { api: 'tags', col: 'tags', kind: 'json' },
  { api: 'source', col: 'source', kind: 'text' },
  { api: 'autoGenerated', col: 'auto_generated', kind: 'bool' },
  { api: 'accessRoles', col: 'access_roles', kind: 'json' },
  { api: 'accessUserIds', col: 'access_user_ids', kind: 'json' },
  { api: 'dedupeHash', col: 'dedupe_hash', kind: 'text' },
  { api: 'originalFileName', col: 'original_file_name', kind: 'text' }
];

const { toColumns, fromRow, insertSql, updateSql, upsertSql } = buildMapper(SPEC, { table: 'knowledge_docs' });

const knowledgeRepo = {
  list: async ({ linkType, linkId, category } = {}) => {
    const where = [];
    const params = [];
    if (linkType) { params.push(linkType); where.push(`link_type = $${params.length}`); }
    if (linkId) { params.push(linkId); where.push(`link_id = $${params.length}`); }
    if (category) { params.push(category); where.push(`category = $${params.length}`); }
    const sql = `SELECT * FROM knowledge_docs ${where.length ? 'WHERE ' + where.join(' AND ') : ''} ORDER BY created_at DESC`;
    const r = await query(sql, params);
    return r.rows.map(fromRow);
  },
  getById: async (id) => {
    const r = await query('SELECT * FROM knowledge_docs WHERE id = $1 LIMIT 1', [String(id || '')]);
    return r.rows[0] ? fromRow(r.rows[0]) : null;
  },
  createWith: async (runner, doc) => {
    const withId = { ...doc, id: doc.id || makeId('DOC') };
    const { text, values } = insertSql(toColumns(withId));
    const r = await runner(text, values);
    return fromRow(r.rows[0]);
  },
  create: async (doc) => knowledgeRepo.createWith(query, doc),
  update: async (id, updates) => {
    const { text, values } = updateSql(id, toColumns({ ...updates, id }));
    const r = await query(text, values);
    return r.rows[0] ? fromRow(r.rows[0]) : null;
  },
  remove: async (id) => {
    await query('DELETE FROM knowledge_docs WHERE id = $1', [String(id || '')]);
    return { ok: true };
  },
  upsertWith: async (runner, obj) => {
    const { text, values } = upsertSql(toColumns({ ...obj, id: obj.id || makeId('DOC') }));
    const r = await runner(text, values);
    return fromRow(r.rows[0]);
  }
};

module.exports = { knowledgeRepo, fromRow };
