// 知识库 repo —— 批次2。注意 updatedAt 是业务字段，映射到 doc_updated_at。
const { query } = require('../db/pool');
const { buildMapper, makeId } = require('./_mapper');

const SPEC = [
  { api: 'id', col: 'id', kind: 'text' },
  { api: 'title', col: 'title', kind: 'text' },
  { api: 'category', col: 'category', kind: 'text' },
  { api: 'format', col: 'format', kind: 'text' },
  { api: 'size', col: 'size', kind: 'text' },
  { api: 'updatedAt', col: 'doc_updated_at', kind: 'text' },
  { api: 'content', col: 'content', kind: 'text' },
  { api: 'summary', col: 'summary', kind: 'text' },
  { api: 'aiVisible', col: 'ai_visible', kind: 'bool' },
  { api: 'sourceUrl', col: 'source_url', kind: 'text' },
  { api: 'linkType', col: 'link_type', kind: 'text' },
  { api: 'linkId', col: 'link_id', kind: 'text' },
  { api: 'linkTitle', col: 'link_title', kind: 'text' },
  { api: 'tags', col: 'tags', kind: 'json' },
  { api: 'source', col: 'source', kind: 'text' },
  { api: 'autoGenerated', col: 'auto_generated', kind: 'bool' },
  { api: 'accessRoles', col: 'access_roles', kind: 'json' },
  { api: 'accessUserIds', col: 'access_user_ids', kind: 'json' },
  { api: 'dedupeHash', col: 'dedupe_hash', kind: 'text' },
  { api: 'originalFileName', col: 'original_file_name', kind: 'text' }
];

const { toColumns, fromRow, insertSql, updateSql, upsertSql } = buildMapper(SPEC, { table: 'knowledge_docs' });

const knowledgeRepo = {
  list: async ({ linkType, linkId, category } = {}) => {
    const where = [];
    const params = [];
    if (linkType) { params.push(linkType); where.push(`link_type = $${params.length}`); }
    if (linkId) { params.push(linkId); where.push(`link_id = $${params.length}`); }
    if (category) { params.push(category); where.push(`category = $${params.length}`); }
    const sql = `SELECT * FROM knowledge_docs ${where.length ? 'WHERE ' + where.join(' AND ') : ''} ORDER BY created_at DESC`;
    const r = await query(sql, params);
    return r.rows.map(fromRow);
  },
  getById: async (id) => {
    const r = await query('SELECT * FROM knowledge_docs WHERE id = $1 LIMIT 1', [String(id || '')]);
    return r.rows[0] ? fromRow(r.rows[0]) : null;
  },
  createWith: async (runner, doc) => {
    const withId = { ...doc, id: doc.id || makeId('DOC') };
    const { text, values } = insertSql(toColumns(withId));
    const r = await runner(text, values);
    return fromRow(r.rows[0]);
  },
  create: async (doc) => knowledgeRepo.createWith(query, doc),
  update: async (id, updates) => {
    const { text, values } = updateSql(id, toColumns({ ...updates, id }));
    const r = await query(text, values);
    return r.rows[0] ? fromRow(r.rows[0]) : null;
  },
  remove: async (id, actor = {}) => {
    /*
      墓碑必须和删除在**同一个事务**里。

      分开写的话，删成功而墓碑没记上，这条记录下次整份写回就又回来了 ——
      比不删还糟，因为人已经以为删掉了。
    */
    const pool = require('../db/pool');
    const { recordDeletion } = require('../services/tombstones');
    await pool.withTransaction(async (client) => {
      await client.query('DELETE FROM knowledge_docs WHERE id = $1', [String(id || '')]);
      await recordDeletion((t, v) => client.query(t, v), {
        entityType: 'knowledge',
        entityId: id,
        deletedBy: actor.userId,
        deletedByName: actor.userName,
        reason: actor.reason
      });
    });

    /*
      提醒规则 4：挂在这份文档上的提醒跟着走。

      不带走的话会变成「点开什么也没有、又消不掉」的死条目 ——
      正是提醒栏被塞满的成因之一。
      每日任务里也有一遍孤儿清理兜底，但那是明天的事；
      人删完文档不该还要等到明天才看不见它的提醒。
    */
    try {
      const { cascadeOnDelete } = require('../services/reminderLifecycle');
      await cascadeOnDelete(pool, 'knowledge', id);
    } catch { /* 清提醒失败不该让删文档也失败 */ }
    return { ok: true };
  },
  upsertWith: async (runner, obj) => {
    const { text, values } = upsertSql(toColumns({ ...obj, id: obj.id || makeId('DOC') }));
    const r = await runner(text, values);
    return fromRow(r.rows[0]);
  }
};

module.exports = { knowledgeRepo, fromRow };
