

import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { Customer, ContactPerson, Status, Contract, Project, CertificateDetail, AuditNode, FollowUpRecord, UserProfile, KnowledgeDoc, RoleID } from '../types';
import { Search, MoreHorizontal, ShieldAlert, BadgeCheck, X, Building, FileText, Briefcase, Globe, Users, Phone, MessageCircle, MapPin, Wallet, Edit3, Save, Plus, Trash2, CalendarClock, Send, Sparkles, Loader2, FileCheck, ArrowRight, Activity, Layers, Target, ChevronRight, Hash, CreditCard, AlignLeft, ScanLine, Eye, Download, Zap, RefreshCw, BellRing, BrainCircuit, MessageSquare, ListTree, Clock, CheckCircle, UploadCloud, Lock } from 'lucide-react';
import { aiService } from '../services/aiService';
import { COMPANY_SERVICES, CERT_LIFECYCLE_RULES } from '../constants';
import { useLocation, useNavigate } from 'react-router-dom';
import { IngestionUploader } from '../components/IngestionUploader';

const Customers = () => {
  const { customers, updateCustomer, addCustomer, addCustomerFollowUp, contracts, projects, addReminder, runSystemScans, generateAuditPlan, updateCertificateAuditStatus, createFollowUpProjectFromCustomer, currentUser, knowledgeDocs, addKnowledgeDoc } = useApp();
  const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [editingData, setEditingData] = useState<Customer | null>(null);
  const location = useLocation();
  const navigate = useNavigate();
  
  const [activeTab, setActiveTab] = useState<'overview' | 'contracts' | 'projects' | 'conversion'>('overview');
  const [isEditing, setIsEditing] = useState(false);
  const [expandedPhonesByCustomerId, setExpandedPhonesByCustomerId] = useState<Record<string, boolean>>({});
  
  // 可转化池逻辑：合作中且（证书即将到期 或 服务满1年）
  const conversionPool = customers.filter(c => {
    if (c.status !== Status.Active) return false;
    
    // 规则1：证书即将到期（<180天）
    const hasExpiringCert = (c.certificates || []).some(cert => {
      if (!cert.expiryDate) return false;
      const days = Math.ceil((new Date(cert.expiryDate).getTime() - Date.now()) / (1000 * 3600 * 24));
      return days > 0 && days <= 180;
    });

    // 规则2：最近一次服务超过1年（潜在复购）
    const hasLongGap = c.lastServiceDate ? 
      (Date.now() - new Date(c.lastServiceDate).getTime()) > 365 * 24 * 3600 * 1000 : false;

    return hasExpiringCert || hasLongGap;
  });

  const canAccessDoc = (doc: KnowledgeDoc) => {
    if (doc.accessUserIds && doc.accessUserIds.length > 0 && !doc.accessUserIds.includes(currentUser.id)) return false;
    if (doc.accessRoles && doc.accessRoles.length > 0 && !doc.accessRoles.some(r => currentUser.roles.includes(r))) return false;
    return true;
  };

  const getCustomerPdcaDocs = (customerId: string) => knowledgeDocs
    .filter(canAccessDoc)
    .filter(doc => doc.category === 'PDCA' && doc.linkType === 'customer' && doc.linkId === customerId)
    .sort((a, b) => (b.updatedAt || '').localeCompare(a.updatedAt || ''));

  const handleCreatePdcaDoc = (customer: Customer) => {
    const nowStr = new Date().toISOString().split('T')[0];
    const newDoc: KnowledgeDoc = {
      id: `DOC-PDCA-MANUAL-${Date.now()}`,
      title: `客户复盘｜${customer.name}｜待补充`,
      category: 'PDCA',
      format: 'Markdown',
      size: '1 KB',
      updatedAt: nowStr,
      content: `# 客户复盘 (PDCA)\n\n## 基本信息\n- 客户：${customer.name}\n- 服务项：\n- 合同/项目：\n\n## P 计划\n- 目标/范围：\n- 负责人：\n\n## D 执行\n- 关键任务与进度：\n\n## C 检查\n- 质量/进度结论：\n- 风险问题：\n\n## A 改进\n- 下一次机会：\n- 经验教训：\n\n`,
      summary: '手动创建的 PDCA 复盘草稿（待补充）。',
      aiVisible: true,
      source: 'manual',
      autoGenerated: false,
      linkType: 'customer',
      linkId: customer.id,
      linkTitle: customer.name,
      tags: ['PDCA', '手动创建'],
      accessRoles: ['ADMIN', 'MANAGER', 'FINANCE'] as RoleID[]
    };
    addKnowledgeDoc(newDoc);
    alert('✅ 已生成 PDCA 复盘草稿，可在知识中心完善。');
  };

  const pdcaDocs = selectedCustomer ? getCustomerPdcaDocs(selectedCustomer.id) : [];
  
  const [filterStatus, setFilterStatus] = useState<'all' | 'paid' | 'unpaid' | 'overdue'>('all');
  const [settlementTypeFilter, setSettlementTypeFilter] = useState<'All' | 'Internal' | 'External'>('All');
  const [isRejectModalOpen, setIsRejectModalOpen] = useState(false);
  const [rejectData, setRejectData] = useState<{contractId: string, receivableId: string, amount: number, customer: string} | null>(null);
  const [rejectReason, setRejectReason] = useState('查无此账 / 金额不符');
  const [isImporting, setIsImporting] = useState(false);

  const [isScanning, setIsScanning] = useState(false);
  const [isCertScanning, setIsCertScanning] = useState(false);

  // Follow-up State
  const [newFollowUpContent, setNewFollowUpContent] = useState('');
  const [newFollowUpType, setNewFollowUpType] = useState<'call' | 'visit' | 'wechat' | 'email'>('call');

  const handleCreateFollowUpProject = () => {
    if (!selectedCustomer) return;
    const certs = (editingData?.certificates || []).filter(c => c.expiryDate);
    const sorted = [...certs].sort((a, b) => a.expiryDate.localeCompare(b.expiryDate));
    const next = sorted[0];
    const projectId = createFollowUpProjectFromCustomer(selectedCustomer.id, {
      certificateId: next?.id,
      expiryDate: next?.expiryDate,
      owner: '销售 / 咨询'
    });
    if (projectId) {
      setSelectedCustomer(null);
      setIsCreating(false);
      navigate('/projects', { state: { openDetailId: projectId } });
    }
  };

  const compressImage = async (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
        const maxWidth = 1024;
        const quality = 0.7;
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = (event) => {
            const img = new Image();
            img.src = event.target?.result as string;
            img.onload = () => {
                const canvas = document.createElement('canvas');
                let width = img.width;
                let height = img.height;
                if (width > maxWidth) {
                    height = Math.round(height * (maxWidth / width));
                    width = maxWidth;
                }
                canvas.width = width;
                canvas.height = height;
                const ctx = canvas.getContext('2d');
                ctx?.drawImage(img, 0, 0, width, height);
                const dataUrl = canvas.toDataURL('image/jpeg', quality);
                resolve(dataUrl.split(',')[1]); 
            };
            img.onerror = reject;
        };
        reader.onerror = reject;
    });
  };

  const normalizeDate = (dateStr: string) => {
      if (!dateStr) return '';
      let clean = dateStr.replace(/[年月日\.]/g, '-').replace(/-$/, '');
      const parts = clean.split('-');
      if (parts.length === 3) {
          return `${parts[0]}-${parts[1].padStart(2, '0')}-${parts[2].padStart(2, '0')}`;
      }
      return clean;
  };

  const getAuditNodeLabel = (type: string) => {
      const map: Record<string, string> = {
          'Initial': '初始审核',
          'Surveillance 1': '第一次监审',
          'Surveillance 2': '第二次监审',
          'Surveillance 3': '第三次监审',
          'Surveillance 4': '第四次监审',
          'Re-certification': '复评换证',
          'Special Audit': '专项审核',
          'Annual Review': '年度审查',
          'Update': '信息更新'
      };
      return map[type] || type;
  };

  const getFollowUpTypeLabel = (type: string) => {
      const map: Record<string, string> = {
          'call': '电话',
          'visit': '拜访',
          'wechat': '微信',
          'email': '邮件',
          'system': '系统'
      };
      return map[type] || type;
  };

  const splitPhones = (raw?: string) => {
    const text = (raw || '').trim();
    if (!text) return [] as string[];
    return text
      .split(/[\s,，、;；\n\r\t]+/g)
      .map(x => x.trim())
      .filter(Boolean);
  };

  const getCustomerPhones = (cust: Customer) => {
    const fromContacts = (cust.contacts || []).flatMap(c => splitPhones(c.mobile));
    const fromMobile = splitPhones(cust.mobile);
    const all = [...fromContacts, ...fromMobile];
    const seen = new Set<string>();
    const unique: string[] = [];
    for (const p of all) {
      if (!p) continue;
      if (seen.has(p)) continue;
      seen.add(p);
      unique.push(p);
    }
    return unique;
  };

  useEffect(() => {
      if (location.state && location.state.openDetailId) {
          const targetCustomer = customers.find(c => c.id === location.state.openDetailId);
          if (targetCustomer) {
              openDetail(targetCustomer);
              window.history.replaceState({}, document.title);
          }
      }
  }, [location, customers]);

  useEffect(() => {
      if (selectedCustomer && !isCreating) {
          const updated = customers.find(c => c.id === selectedCustomer.id);
          if (updated) {
              setSelectedCustomer(updated);
              if (!isEditing) setEditingData(updated);
          }
      }
  }, [customers, isCreating, isEditing, selectedCustomer]);

  const openDetail = (cust: Customer) => {
      setSelectedCustomer(cust);
      setIsCreating(false);
      setEditingData({
          ...cust,
          contacts: cust.contacts && cust.contacts.length > 0 ? cust.contacts : [{
              id: `c-init-${Date.now()}`,
              name: cust.contactPerson,
              mobile: cust.mobile,
              isPrimary: true
          }]
      });
      setIsEditing(false);
      setActiveTab('overview');
  };

  const handleSaveEdit = () => { if (!editingData || !editingData.name) { alert("请输入客户名称"); return; } const primaryContact = editingData.contacts?.find(c => c.isPrimary) || editingData.contacts?.[0]; const dataToSave = { ...editingData, contactPerson: primaryContact?.name || editingData.contactPerson, mobile: primaryContact?.mobile || editingData.mobile, }; if (isCreating) { addCustomer(dataToSave as Omit<Customer, 'id'>); setIsCreating(false); setIsEditing(false); setSelectedCustomer(null); } else if (selectedCustomer) { updateCustomer(selectedCustomer.id, dataToSave); setIsEditing(false); } };

  const handleAddFollowUp = () => {
      if (!selectedCustomer || !newFollowUpContent.trim()) return;
      const record: Omit<FollowUpRecord, 'id'> = {
          date: new Date().toISOString().split('T')[0],
          type: newFollowUpType,
          content: newFollowUpContent,
          operator: '我'
      };
      addCustomerFollowUp(selectedCustomer.id, record);
      setNewFollowUpContent('');
  };

  const handleUpsellScript = () => {
      if (!editingData) return;
      
      const contextData = {
          name: editingData.name,
          info: `
- 行业：${editingData.industry}
- 已有证书：${editingData.existingCertifications?.join(', ') || '无'}
- 潜在目标：${editingData.targetCertifications || '增值服务'}
- 最近动态：${editingData.followUpRecords?.[0]?.content || '无'}
          `.trim()
      };

      const event = new CustomEvent('trigger-ai-script', { detail: { context: contextData } });
      window.dispatchEvent(event);
  };

  const handleOCRUpload = async (e: React.ChangeEvent<HTMLInputElement>) => { 
      // OCR logic for business license identification
      const file = e.target.files?.[0]; 
      if (!file || !editingData) return; 
      setIsScanning(true); 
      try { 
          let base64Data: string; 
          let mimeType = 'image/jpeg';

          if (file.type.startsWith('image/')) { 
              base64Data = await compressImage(file); 
              mimeType = 'image/jpeg';
          } else { 
              base64Data = await new Promise<string>((resolve, reject) => { 
                  const reader = new FileReader(); 
                  reader.readAsDataURL(file); 
                  reader.onload = () => resolve((reader.result as string).split(',')[1]); 
                  reader.onerror = reject; 
              }); 
              mimeType = file.type || 'application/pdf';
          } 
          const prompt = ` Task: Extract business info. Output JSON only: { "company": "Company Name", "legalRepresentative": "Legal Rep", "registeredCapital": "Capital", "foundingDate": "YYYY-MM-DD", "unifiedSocialCreditCode": "Credit Code", "registeredAddress": "Address", "businessScope": "Scope", "industry": "Industry", "companyType": "Type", "operationStatus": "Status" } `; 
          
          const result = await aiService.generateJSON('kimi-k2.5', [{ inlineData: { mimeType: mimeType, data: base64Data } }, { text: prompt }]);
          
          if (!result || !result.company) {
              throw new Error("未能识别有效执照信息，请检查图片清晰度。");
          }

          setEditingData(prev => prev ? ({ ...prev, name: result.company || prev.name, legalRepresentative: result.legalRepresentative || prev.legalRepresentative, registeredCapital: result.registeredCapital || prev.registeredCapital, foundingDate: normalizeDate(result.foundingDate) || prev.foundingDate, unifiedSocialCreditCode: result.unifiedSocialCreditCode || prev.unifiedSocialCreditCode, registeredAddress: result.registeredAddress || prev.registeredAddress, businessScope: result.businessScope || prev.businessScope, industry: result.industry || prev.industry, companyType: result.companyType || prev.companyType, operationStatus: result.operationStatus || prev.operationStatus }) : null); 
          alert("✅ 识别成功！"); 
      } catch (error: any) { 
          console.error("OCR Failed", error); 
          alert(`识别失败：${error.message || '请重试或手动填写'}`); 
      } finally { 
          setIsScanning(false); 
          e.target.value = ''; 
      } 
  };

  const handleCertOCR = async (e: React.ChangeEvent<HTMLInputElement>) => {
      // OCR logic for certificate identification
      const file = e.target.files?.[0];
      if (!file || !editingData) return;
      
      setIsCertScanning(true);
      try {
          let base64Data: string;
          let mimeType = 'image/jpeg';

          if (file.type.startsWith('image/')) {
              base64Data = await compressImage(file);
              mimeType = 'image/jpeg';
          } else {
              base64Data = await new Promise<string>((resolve, reject) => {
                  const reader = new FileReader();
                  reader.readAsDataURL(file);
                  reader.onload = () => resolve((reader.result as string).split(',')[1]);
                  reader.onerror = reject;
              });
              mimeType = file.type || 'application/pdf';
          }

          const prompt = `
            Task: Extract certificate details from image.
            Return JSON only: {
                "name": "Standard Name (e.g. ISO 9001:2015)",
                "issuingBody": "Certification Body Name",
                "issueDate": "YYYY-MM-DD",
                "expiryDate": "YYYY-MM-DD",
                "number": "Certificate Number"
            }
          `;
          
          const result = await aiService.generateJSON('kimi-k2.5', [{ inlineData: { mimeType: mimeType, data: base64Data } }, { text: prompt }]);
          
          if (!result || !result.name) {
              console.warn("Cert OCR returned incomplete data:", result);
              alert("无法识别证书内容，请尝试上传更清晰的图片或手动输入。");
              return;
          }

          let rule: any = 'SYSTEM_3Y'; 
          const upperName = result.name.toUpperCase();
          if (upperName.includes('IATF') || upperName.includes('16949')) rule = 'IATF_3Y';
          else if (upperName.includes('CCC') || upperName.includes('CQC')) rule = 'PRODUCT_5Y';
          else if (upperName.includes('FDA')) rule = 'FDA_MED_5Y';
          else if (upperName.includes('高新')) rule = 'HIGHTECH_3Y';
          else if (upperName.includes('专精特新')) rule = 'SPECIALIZED_3Y';
          else if (upperName.includes('SC') && upperName.includes('食品')) rule = 'SC_5Y';

          const issueDate = normalizeDate(result.issueDate);
          const expiryDate = normalizeDate(result.expiryDate);

          const newCert: CertificateDetail = {
              id: `cert-${Date.now()}`,
              name: result.name || '未知证书',
              number: result.number,
              issuingBody: result.issuingBody,
              issueDate: issueDate,
              expiryDate: expiryDate,
              status: 'Valid',
              cycleRule: rule,
              auditPlan: issueDate ? generateAuditPlan(issueDate, rule) : []
          };

          setEditingData(prev => prev ? ({
              ...prev,
              certificates: [...(prev.certificates || []), newCert],
              existingCertifications: [...new Set([...(prev.existingCertifications || []), result.name])]
          }) : null);

          alert(`✅ 证书识别成功！`);

      } catch (error: any) {
          console.error("Cert OCR Failed", error);
          alert(`证书识别服务暂时不可用，请稍后再试：${error.message}`);
      } finally {
          setIsCertScanning(false);
          e.target.value = '';
      }
  };

  const handleGenerateAuditPlan = (index: number) => { if (!editingData?.certificates) return; const cert = editingData.certificates[index]; if (!cert.issueDate || !cert.cycleRule) { alert("请先设置发证日期 (Issue Date) 和监管规则 (Rule)"); return; } const plan = generateAuditPlan(cert.issueDate, cert.cycleRule); const newCerts = [...editingData.certificates]; newCerts[index] = { ...cert, auditPlan: plan }; setEditingData({ ...editingData, certificates: newCerts }); alert(`已生成 ${plan.length} 个监管节点！`); };

  const updateCertificate = (index: number, field: keyof CertificateDetail, value: any) => {
    if (!editingData?.certificates) return;
    const newCerts = [...editingData.certificates];
    newCerts[index] = { ...newCerts[index], [field]: value };
    setEditingData({ ...editingData, certificates: newCerts });
  };

  const toggleReceivableStatus = (cid: string, rid: string) => { useApp().toggleReceivableStatus(cid, rid); };
  const openRejectModal = (contractId: string, receivableId: string, amount: number, customer: string) => { setRejectData({ contractId, receivableId, amount, customer }); setIsRejectModalOpen(true); };

  const isFinancialVisible = (cust: Customer) => {
      // Rule 10: Admin/Boss can see all; Consultant can only see own customers
      if (currentUser.activeRole === 'ADMIN' || currentUser.activeRole === 'MANAGER') return true;
      if (currentUser.activeRole === 'CONSULTANT') {
          // Check ownership (simple name match for MVP, should be ID based in prod)
          return cust.contactPerson === currentUser.name || cust.name.includes(currentUser.name); // Simplified logic
      }
      return false;
  };

  return (
    <div className="p-6">
       <div className="mb-6 flex justify-between items-center">
           <div>
               <h1 className="text-2xl font-bold text-gray-900">客户管理</h1>
               <p className="text-sm text-gray-500 mt-1">360° 客户视图与全生命周期经营</p>
           </div>
           <button onClick={() => { setIsCreating(true); setIsEditing(true); setEditingData({ id: 'temp', name: '', contactPerson: '', totalValue: 0, riskStatus: 'low', activeContracts: 0, contacts: [{ id: 'c1', name: '', isPrimary: true }] }); setSelectedCustomer({ id: 'temp', name: '', contactPerson: '', totalValue: 0, riskStatus: 'low', activeContracts: 0 } as Customer); }} className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700 shadow-sm whitespace-nowrap transition-all active:scale-95 font-bold text-sm" > <Plus className="w-4 h-4 mr-2" /> 新建客户 </button>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
         <div className="p-4 border-b border-gray-100 flex items-center justify-between bg-gray-50/30">
            <div className="relative w-full md:w-96">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                <input type="text" placeholder="搜索客户..." className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-500/20 text-sm bg-white" />
            </div>
        </div>
        
        <div className="hidden md:block overflow-x-auto">
            <table className="w-full text-sm text-left">
                <thead className="bg-gray-50/50 text-gray-600 font-bold text-sm uppercase tracking-wider border-b border-gray-100">
                    <tr>
                        <th className="px-6 py-4">客户名称</th>
                        <th className="px-6 py-4">已获证书</th>
                        <th className="px-6 py-4">风险等级</th>
                        {activeTab === 'conversion' && <th className="px-6 py-4">转化机会</th>}
                        <th className="px-6 py-4 text-right">操作</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                    {(activeTab === 'conversion' ? conversionPool : customers).map(cust => (
                        <tr key={cust.id} className="hover:bg-gray-50/80 cursor-pointer transition-colors group" onClick={() => openDetail(cust)}>
                            <td className="px-6 py-5">
                                <div className="font-black text-gray-900 text-base">{cust.name}</div>
                                {(() => {
                                  const phones = getCustomerPhones(cust);
                                  const preview = phones.slice(0, 2).join(', ') || '-';
                                  const extra = Math.max(0, phones.length - 2);
                                  const expanded = Boolean(expandedPhonesByCustomerId[cust.id]);
                                  return (
                                    <div className="mt-1">
                                      <div className="text-sm text-gray-500 flex items-center gap-1 flex-wrap">
                                        <span>{cust.contactPerson} • {preview}</span>
                                        {extra > 0 && (
                                          <button
                                            onClick={(e) => {
                                              e.stopPropagation();
                                              setExpandedPhonesByCustomerId(prev => ({ ...prev, [cust.id]: !prev[cust.id] }));
                                            }}
                                            className="text-xs font-black text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full border border-indigo-100 hover:bg-indigo-100"
                                          >
                                            {expanded ? '收起' : `+${extra}`}
                                          </button>
                                        )}
                                      </div>
                                      {expanded && extra > 0 && (
                                        <div
                                          onClick={(e) => e.stopPropagation()}
                                          className="text-xs text-gray-400 mt-1 font-mono break-all"
                                        >
                                          {phones.slice(2).join(', ')}
                                        </div>
                                      )}
                                    </div>
                                  );
                                })()}
                            </td>
                            <td className="px-6 py-5">
                                <div className="flex flex-wrap gap-1">
                                    {cust.existingCertifications && cust.existingCertifications.length > 0 ? 
                                        cust.existingCertifications.slice(0,2).map((c,i) => (
                                            <span key={i} className="text-xs bg-green-50 text-green-700 px-1.5 py-0.5 rounded border border-green-100 font-bold uppercase tracking-tight">{c}</span>
                                        )) : <span className="text-sm text-gray-400">-</span>
                                    }
                                </div>
                            </td>
                            <td className="px-6 py-5">
                                <div className="flex items-center">
                                    {cust.riskStatus === 'high' ? (
                                        <span className="flex items-center px-2 py-1 bg-red-100 text-red-800 rounded text-xs font-bold uppercase tracking-tight"> <ShieldAlert className="w-3 h-3 mr-1" /> 高风险 </span>
                                    ) : (
                                        <span className="flex items-center px-2 py-1 bg-green-100 text-green-800 rounded text-xs font-bold uppercase tracking-tight"> <BadgeCheck className="w-3 h-3 mr-1" /> 正常 </span>
                                    )}
                                </div>
                            </td>
                            {activeTab === 'conversion' && (
                              <td className="px-6 py-5">
                                <div className="text-sm text-purple-600 font-bold flex items-center">
                                  <Sparkles className="w-3 h-3 mr-1" />
                                  建议跟进
                                </div>
                                <div className="text-xs text-gray-400 mt-0.5">
                                  {(cust.certificates || []).some(c => c.expiryDate && new Date(c.expiryDate).getTime() - Date.now() < 180 * 24 * 3600 * 1000) 
                                    ? '证书即将到期' 
                                    : '服务满1年'}
                                </div>
                              </td>
                            )}
                            <td className="px-6 py-5 text-right"> <button className="text-gray-400 hover:text-blue-600 p-2 hover:bg-blue-50 rounded-lg transition-colors"> <MoreHorizontal className="w-5 h-5" /> </button> </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>

        {/* Mobile View */}
        <div className="md:hidden divide-y divide-gray-100">
            {customers.map(cust => (
                <div key={cust.id} className="p-4 active:bg-gray-50 transition-colors" onClick={() => openDetail(cust)}>
                    <div className="flex justify-between items-start mb-2">
                        <div className="font-black text-gray-900 line-clamp-1 mr-2 text-base">{cust.name}</div>
                        {cust.riskStatus === 'high' ? (
                            <span className="flex items-center px-2 py-0.5 bg-red-100 text-red-800 rounded text-xs font-bold uppercase tracking-tight whitespace-nowrap"> <ShieldAlert className="w-3 h-3 mr-1" /> 高风险 </span>
                        ) : (
                            <span className="flex items-center px-2 py-0.5 bg-green-100 text-green-800 rounded text-xs font-bold uppercase tracking-tight whitespace-nowrap"> <BadgeCheck className="w-3 h-3 mr-1" /> 正常 </span>
                        )}
                    </div>
                    {(() => {
                      const phones = getCustomerPhones(cust);
                      const preview = phones.slice(0, 2).join(', ') || '-';
                      const extra = Math.max(0, phones.length - 2);
                      const expanded = Boolean(expandedPhonesByCustomerId[cust.id]);
                      return (
                        <div className="mb-2">
                          <div className="text-sm text-gray-500 flex items-center gap-1 flex-wrap">
                            <span>{cust.contactPerson} • {preview}</span>
                            {extra > 0 && (
                              <button
                                onClick={(e) => {
                                  e.stopPropagation();
                                  setExpandedPhonesByCustomerId(prev => ({ ...prev, [cust.id]: !prev[cust.id] }));
                                }}
                                className="text-xs font-black text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full border border-indigo-100 hover:bg-indigo-100"
                              >
                                {expanded ? '收起' : `+${extra}`}
                              </button>
                            )}
                          </div>
                          {expanded && extra > 0 && (
                            <div
                              onClick={(e) => e.stopPropagation()}
                              className="text-xs text-gray-400 mt-1 font-mono break-all"
                            >
                              {phones.slice(2).join(', ')}
                            </div>
                          )}
                        </div>
                      );
                    })()}
                    <div className="flex flex-wrap gap-1">
                        {cust.existingCertifications && cust.existingCertifications.length > 0 ? 
                            cust.existingCertifications.slice(0,3).map((c,i) => (
                                <span key={i} className="text-xs bg-gray-50 text-gray-600 px-1.5 py-0.5 rounded border border-gray-100 font-bold uppercase tracking-tight">{c}</span>
                            )) : <span className="text-xs text-gray-300">暂无证书</span>
                        }
                    </div>
                </div>
            ))}
        </div>
      </div>

       {selectedCustomer && editingData && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-2 md:p-6 backdrop-blur-sm">
             <div className="bg-white rounded-3xl shadow-xl w-full max-w-6xl max-h-[95vh] overflow-hidden flex flex-col animate-in fade-in zoom-in duration-200 border border-gray-100">
                
                <div className="bg-white border-b border-gray-100 p-6 flex flex-col md:flex-row justify-between items-start shrink-0">
                    <div className="flex items-center space-x-4 mb-4 md:mb-0 w-full md:w-auto">
                        <div className="w-14 h-14 bg-indigo-50 rounded-2xl flex items-center justify-center shrink-0 border border-indigo-100"> <Building className="w-7 h-7 text-indigo-600" /> </div>
                        <div className="min-w-0 flex-1">
                            {isEditing ? ( <input className="text-2xl font-black text-gray-900 border-b border-gray-300 focus:border-indigo-500 outline-none w-full md:w-96 mb-1" value={editingData.name} onChange={e => setEditingData({...editingData, name: e.target.value})} placeholder="请输入客户名称" /> ) : ( <h2 className="text-2xl font-black text-gray-900 truncate tracking-tight">{selectedCustomer.name}</h2> )}
                        </div>
                    </div>
                    <div className="flex items-center space-x-2 md:space-x-3 w-full md:w-auto justify-end">
                        <button onClick={handleCreateFollowUpProject} className="px-3 py-2 bg-amber-600 text-white rounded-xl hover:bg-amber-700 text-sm font-bold flex items-center transition-all active:scale-95 shadow-md"> <Briefcase className="w-4 h-4 mr-1.5" /> 生成跟进项目 </button>
                        <button onClick={handleUpsellScript} className="px-3 py-2 bg-gradient-to-r from-purple-500 to-indigo-600 text-white rounded-xl hover:shadow-lg text-sm font-bold flex items-center transition-all active:scale-95 shadow-md"> <MessageSquare className="w-4 h-4 mr-1.5" /> 二次开发话术 </button>
                        {!isEditing ? ( <button onClick={() => setIsEditing(true)} className="px-4 py-2 border border-gray-200 bg-white text-gray-700 rounded-xl hover:bg-gray-50 flex items-center text-sm font-bold transition-colors"> <Edit3 className="w-4 h-4 mr-2" /> 编辑 </button> ) : ( <button onClick={handleSaveEdit} className="px-4 py-2 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 flex items-center text-sm font-bold transition-colors shadow-lg shadow-indigo-200"> <Save className="w-4 h-4 mr-2" /> 保存 </button> )}
                        <button onClick={() => { setSelectedCustomer(null); setIsCreating(false); }} className="p-2 hover:bg-gray-100 rounded-full text-gray-500 transition-colors"> <X className="w-6 h-6" /> </button>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-6 md:p-8 bg-gray-50/50">
                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                            <div className="lg:col-span-2 space-y-8">
                                {/* 1. 客户关系档案 (PDCA) */}
                                <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                                    <div className="flex justify-between items-center mb-4">
                                        <h3 className="text-lg font-bold text-gray-900 flex items-center"> 
                                            <Activity className="w-4 h-4 mr-2 text-rose-600" /> 客户关系档案 (PDCA)
                                        </h3>
                                    </div>
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4">
                                        <div className="bg-rose-50 rounded-xl p-4 border border-rose-100">
                                            <div className="text-xs font-bold text-rose-400 uppercase mb-1">累计消费 (Total)</div>
                                            {isFinancialVisible(selectedCustomer) ? (
                                                <div className="text-2xl font-black text-rose-900">¥{(editingData.totalAmount || 0).toLocaleString()}</div>
                                            ) : (
                                                <div className="text-2xl font-black text-gray-300 flex items-center"><Lock className="w-4 h-4 mr-1"/> ***</div>
                                            )}
                                        </div>
                                        <div className="bg-blue-50 rounded-xl p-4 border border-blue-100">
                                            <div className="text-xs font-bold text-blue-400 uppercase mb-1">最近项目 (Verified)</div>
                                            <div className="font-bold text-blue-900 text-sm truncate">{editingData.lastProjectType || '暂无'}</div>
                                            <div className="text-xs text-blue-500 mt-1">{editingData.lastProjectAt || '-'}</div>
                                        </div>
                                        <div className="bg-amber-50 rounded-xl p-4 border border-amber-100">
                                            <div className="text-xs font-bold text-amber-400 uppercase mb-1">下一次机会</div>
                                            <div className="font-bold text-amber-900 text-sm">{editingData.nextOpportunity || '待评估'}</div>
                                        </div>
                                        <div className="bg-purple-50 rounded-xl p-4 border border-purple-100">
                                            <div className="text-xs font-bold text-purple-400 uppercase mb-1">客户评级</div>
                                            {isFinancialVisible(selectedCustomer) ? (
                                                <div className="text-2xl font-black text-purple-900">{editingData.level || 'C'} <span className="text-xs font-normal text-purple-600">级</span></div>
                                            ) : (
                                                <div className="text-2xl font-black text-gray-300 flex items-center"><Lock className="w-4 h-4 mr-1"/> *</div>
                                            )}
                                        </div>
                                    </div>
                                    <div className="bg-gray-50 rounded-xl p-4 border border-gray-100">
                                        <div className="text-xs font-bold text-gray-400 uppercase mb-2">客户认知沉淀 (Notes)</div>
                                        {isEditing ? (
                                            <textarea 
                                                className="w-full bg-white border border-gray-200 rounded-lg p-3 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                                                rows={3}
                                                placeholder="在此记录客户画像、偏好、决策链等长期价值信息..."
                                                value={editingData.customerNotes || ''}
                                                onChange={e => setEditingData({...editingData, customerNotes: e.target.value})}
                                            />
                                        ) : (
                                            <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                                                {editingData.customerNotes || '暂无沉淀'}
                                            </p>
                                        )}
                                    </div>
                                    <div className="mt-4 bg-indigo-50/60 rounded-xl p-4 border border-indigo-100">
                                        <div className="flex items-center justify-between mb-3">
                                            <div className="text-xs font-bold text-indigo-600 uppercase flex items-center">
                                                <BrainCircuit className="w-4 h-4 mr-1.5" /> 客户复盘档案 (PDCA)
                                            </div>
                                            <button
                                                onClick={() => selectedCustomer && handleCreatePdcaDoc(selectedCustomer)}
                                                className="text-xs font-bold text-indigo-600 hover:text-indigo-700"
                                            >
                                                生成复盘草稿
                                            </button>
                                        </div>
                                        {pdcaDocs.length > 0 ? (
                                            <div className="space-y-2">
                                                {pdcaDocs.slice(0, 3).map(doc => (
                                                    <div key={doc.id} className="flex items-center justify-between bg-white rounded-lg px-3 py-2 border border-indigo-100">
                                                        <div className="min-w-0">
                                                            <div className="text-sm font-bold text-gray-800 truncate">{doc.title}</div>
                                                            <div className="text-[11px] text-gray-400">{doc.updatedAt || '-'}</div>
                                                        </div>
                                                        <span className="text-[10px] font-bold text-indigo-600 bg-indigo-50 px-2 py-1 rounded-full border border-indigo-100">
                                                            已归档
                                                        </span>
                                                    </div>
                                                ))}
                                                {pdcaDocs.length > 3 && (
                                                    <div className="text-[11px] text-indigo-600 font-bold">更多复盘请前往「知识中心」查看</div>
                                                )}
                                            </div>
                                        ) : (
                                            <div className="text-xs text-gray-500">暂无复盘记录，建议在回款完成后自动归档或手动补充。</div>
                                        )}
                                    </div>
                                </div>

                                <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                                    <div className="flex justify-between items-center mb-6">
                                        <h3 className="text-lg font-bold text-gray-900 flex items-center"> <FileCheck className="w-4 h-4 mr-2 text-green-600" /> 认证证书与监管周期 </h3>
                                        <div className="flex items-center space-x-2">
                                            {isEditing && (
                                                <div className="w-40">
                                                    <IngestionUploader 
                                                        source="certificate"
                                                        label="智能识别"
                                                        compact={true}
                                                        onSuccess={(result) => {
                                                            const certs = result.data; // CertificateDetail[]
                                                            if (certs && certs.length > 0) {
                                                                const newCert = certs[0];
                                                                const issueDate = normalizeDate(newCert.issueDate);
                                                                const expiryDate = normalizeDate(newCert.expiryDate);
                                                                const finalCert: CertificateDetail = {
                                                                    ...newCert,
                                                                    issueDate,
                                                                    expiryDate,
                                                                    auditPlan: issueDate ? generateAuditPlan(issueDate, newCert.cycleRule || 'SYSTEM_3Y') : []
                                                                };
                                                                
                                                                setEditingData(prev => prev ? ({
                                                                    ...prev,
                                                                    certificates: [...(prev.certificates || []), finalCert],
                                                                    existingCertifications: [...new Set([...(prev.existingCertifications || []), finalCert.name])]
                                                                }) : null);
                                                                alert(`✅ 识别成功！已添加证书：${finalCert.name}`);
                                                            }
                                                        }}
                                                    />
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                    <div className="space-y-4">
                                        {editingData.certificates?.map((cert, idx) => (
                                            <div key={cert.id} className="border border-gray-100 rounded-xl p-4 bg-gray-50/30">
                                                <div className="flex justify-between items-start mb-2">
                                                    <div className="flex items-center space-x-2">
                                                        {isEditing ? ( <input className="font-bold text-sm bg-white border rounded px-1 w-32" value={cert.name} onChange={e => updateCertificate(idx, 'name', e.target.value)} placeholder="证书名称" /> ) : ( <span className="font-bold text-gray-900 text-sm">{cert.name}</span> )}
                                                        <span className={`text-xs px-1.5 py-0.5 rounded border font-bold uppercase tracking-tight ${cert.status === 'Valid' ? 'bg-green-50 text-green-700 border-green-100' : 'bg-red-50 text-red-700 border-red-100'}`}> {cert.status === 'Valid' ? '有效' : '已失效/过期'} </span>
                                                    </div>
                                                </div>
                                                <div className="text-sm text-gray-500 flex flex-wrap gap-6 mb-3 border-b border-gray-200 pb-3">
                                                    <div className="flex items-center"> <span className="mr-2 font-bold text-gray-400">发证机构:</span> {isEditing ? <input className="border-b bg-transparent w-24" value={cert.issuingBody} onChange={e => updateCertificate(idx, 'issuingBody', e.target.value)} /> : (cert.issuingBody || '-')} </div>
                                                    <div className="flex items-center"> <span className="mr-2 font-bold text-gray-400">监管规则:</span> {isEditing ? ( <select className="border rounded px-1 bg-white" value={cert.cycleRule || 'ISO_3Y'} onChange={e => updateCertificate(idx, 'cycleRule', e.target.value)}> {Object.entries(CERT_LIFECYCLE_RULES).map(([key, rule]) => ( <option key={key} value={key}>{rule.name}</option> ))} </select> ) : ( <span className="bg-white border border-gray-200 px-2 py-0.5 rounded font-mono text-xs">{(CERT_LIFECYCLE_RULES as any)[cert.cycleRule as string]?.name || cert.cycleRule}</span> )} </div>
                                                </div>
                                                {cert.auditPlan && cert.auditPlan.length > 0 ? (
                                                    <div className="relative pt-2 pb-1">
                                                        <div className="absolute top-[22px] left-0 w-full h-0.5 bg-gray-200 -z-0"></div>
                                                        <div className="flex justify-between relative z-10">
                                                            {cert.auditPlan.map((node) => (
                                                                <div key={node.id} className="flex flex-col items-center group/node relative">
                                                                    <div className={`w-2.5 h-2.5 rounded-full border-2 mb-1.5 ${ node.status === 'Completed' ? 'bg-green-500 border-green-500' : 'bg-white border-gray-300' }`}></div>
                                                                    <span className="text-xs font-bold text-gray-600 uppercase tracking-tight">{getAuditNodeLabel(node.type)}</span>
                                                                    <span className="text-xs text-gray-400 font-mono mt-0.5">{node.plannedDate}</span>
                                                                </div>
                                                            ))}
                                                        </div>
                                                    </div>
                                                ) : ( <div className="text-center py-2"> {isEditing && ( <button onClick={() => handleGenerateAuditPlan(idx)} className="text-xs font-bold text-indigo-600 bg-indigo-50 px-3 py-1.5 rounded-lg border border-indigo-100 flex items-center mx-auto hover:bg-indigo-100 transition-colors"> <ListTree className="w-3 h-3 mr-1" /> 生成监管计划 </button> )} </div> )}
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>
                            <div className="space-y-8">
                                <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                                    <div className="flex justify-between items-center mb-4">
                                        <h3 className="text-lg font-bold text-gray-900 flex items-center">
                                            <Phone className="w-4 h-4 mr-2 text-indigo-600" /> 联系人与电话
                                        </h3>
                                        <span className="text-xs font-black text-gray-400 uppercase tracking-widest">
                                            共 {getCustomerPhones(editingData).length} 个
                                        </span>
                                    </div>
                                    <div className="space-y-3">
                                        <div className="text-sm font-black text-gray-900">{editingData.contactPerson || '-'}</div>
                                        {getCustomerPhones(editingData).length > 0 ? (
                                            <div className="flex flex-wrap gap-2">
                                                {getCustomerPhones(editingData).map((p, idx) => (
                                                    <span key={`${p}-${idx}`} className="text-xs font-black bg-gray-50 text-gray-700 px-2 py-1 rounded-full border border-gray-200 font-mono">
                                                        {p}
                                                    </span>
                                                ))}
                                            </div>
                                        ) : (
                                            <div className="text-sm text-gray-400 font-bold">暂无电话</div>
                                        )}
                                    </div>
                                </div>
                                <div className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm flex flex-col h-[400px]">
                                    <h3 className="text-lg font-bold text-gray-900 flex items-center mb-4 shrink-0"> 
                                        <MessageCircle className="w-4 h-4 mr-2 text-indigo-600" /> 跟进记录 
                                    </h3>
                                    <div className="flex-1 overflow-y-auto space-y-4 mb-4 pr-2 custom-scrollbar">
                                        {editingData.followUpRecords && editingData.followUpRecords.length > 0 ? (
                                            editingData.followUpRecords.map(record => (
                                                <div key={record.id} className="flex flex-col relative pl-4 border-l-2 border-gray-100">
                                                    <div className="absolute -left-[5px] top-1.5 w-2.5 h-2.5 rounded-full bg-indigo-200"></div>
                                                    <div className="text-xs text-gray-400 font-mono mb-1">{record.date} • {record.operator} • {getFollowUpTypeLabel(record.type)}</div>
                                                    <p className="text-sm text-gray-700 bg-gray-50 p-2 rounded-lg">{record.content}</p>
                                                </div>
                                            ))
                                        ) : (
                                            <div className="text-center text-gray-300 text-sm py-10">暂无跟进记录</div>
                                        )}
                                    </div>
                                    <div className="shrink-0 bg-gray-50 p-3 rounded-xl border border-gray-200">
                                        <div className="flex space-x-2 mb-2">
                                            {['call', 'visit', 'wechat', 'email'].map(t => (
                                                <button 
                                                    key={t} 
                                                    onClick={() => setNewFollowUpType(t as any)}
                                                    className={`text-xs px-2 py-1 rounded font-bold uppercase ${newFollowUpType === t ? 'bg-indigo-600 text-white' : 'bg-white border text-gray-500'}`}
                                                >
                                                    {getFollowUpTypeLabel(t)}
                                                </button>
                                            ))}
                                        </div>
                                        <div className="flex items-center space-x-2">
                                            <input 
                                                className="flex-1 text-sm bg-white border border-gray-200 rounded-lg px-2 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-100" 
                                                placeholder="输入跟进情况..." 
                                                value={newFollowUpContent}
                                                onChange={e => setNewFollowUpContent(e.target.value)}
                                                onKeyDown={e => e.key === 'Enter' && handleAddFollowUp()}
                                            />
                                            <button onClick={handleAddFollowUp} className="p-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">
                                                <Send className="w-3 h-3" />
                                            </button>
                                        </div>
                                    </div>
                                </div>

                                <section className="bg-white p-6 rounded-2xl border border-gray-100 shadow-sm">
                                     <div className="flex justify-between items-center mb-6 border-b border-gray-50 pb-4"> <h3 className="text-lg font-bold text-gray-900 flex items-center"> <FileText className="w-4 h-4 mr-2 text-blue-600" /> 工商主体信息 </h3> {isEditing && ( <div className="relative"> <input type="file" className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10" accept="image/*,.pdf" onChange={handleOCRUpload} disabled={isScanning} /> <button type="button" className="flex items-center text-xs bg-indigo-50 text-indigo-600 hover:bg-indigo-100 px-2 py-1 rounded-lg transition-colors font-bold border border-indigo-100" > {isScanning ? <Loader2 className="w-3 h-3 mr-1 animate-spin" /> : <ScanLine className="w-3 h-3 mr-1" />} OCR填充 </button> </div> )} </div>
                                     <div className="space-y-4 text-sm">
                                        {[
                                            { label: '法定代表人', field: 'legalRepresentative' },
                                            { label: '注册资本', field: 'registeredCapital' },
                                            { label: '成立日期', field: 'foundingDate' },
                                            { label: '信用代码', field: 'unifiedSocialCreditCode' },
                                            // 新增字段
                                            { label: '注册地址', field: 'registeredAddress' },
                                            { label: '企业类型', field: 'companyType' },
                                            { label: '经营状态', field: 'operationStatus' },
                                        ].map(item => (
                                            <div key={item.field} className="flex flex-col space-y-1">
                                                <span className="text-xs font-bold text-gray-400 uppercase">{item.label}</span>
                                                {isEditing ? (
                                                    <input 
                                                        className="w-full border-b border-gray-300 outline-none py-1 font-mono text-sm" 
                                                        value={(editingData as any)[item.field] || ''} 
                                                        onChange={e => setEditingData({...editingData!, [item.field]: e.target.value})} 
                                                    />
                                                ) : (
                                                    <span className="font-bold text-gray-900 font-mono break-all">{(selectedCustomer as any)[item.field] || '-'}</span>
                                                )}
                                            </div>
                                        ))}
                                        
                                        <div className="flex flex-col space-y-1 pt-2">
                                            <span className="text-xs font-bold text-gray-400 uppercase">经营范围</span>
                                            {isEditing ? (
                                                <textarea 
                                                    className="w-full border border-gray-200 rounded p-2 text-xs h-20 bg-white focus:outline-none focus:border-indigo-500"
                                                    value={editingData.businessScope || ''}
                                                    onChange={e => setEditingData({...editingData!, businessScope: e.target.value})}
                                                />
                                            ) : (
                                                <p className="text-xs text-gray-700 leading-relaxed bg-gray-50 p-2 rounded max-h-32 overflow-y-auto">
                                                    {selectedCustomer.businessScope || '-'}
                                                </p>
                                            )}
                                        </div>
                                     </div>
                                </section>
                            </div>
                        </div>
                </div>
             </div>
        </div>
      )}
    </div>
  );
};

export default Customers;
